// <auto-generated />
namespace WebCujae.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Se_incorporo_la_eliminacion_en_cascada_de_Evento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Se_incorporo_la_eliminacion_en_cascada_de_Evento));
        
        string IMigrationMetadata.Id
        {
            get { return "201807041919590_Se_incorporo_la_eliminacion_en_cascada_de_Evento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
